USE DevelopmentDB;

ALTER TABLE developers ADD SALARY INT;

UPDATE developers SET SALARY = 2700 WHERE ID = '1';
UPDATE developers SET SALARY = 2000 WHERE ID = '2';
UPDATE developers SET SALARY = 2100 WHERE ID = '3';
UPDATE developers SET SALARY = 1000 WHERE ID = '4';
UPDATE developers SET SALARY = 1700 WHERE ID = '5';
UPDATE developers SET SALARY = 3000 WHERE ID = '6';
UPDATE developers SET SALARY = 2770 WHERE ID = '7';
UPDATE developers SET SALARY = 2350 WHERE ID = '8';
UPDATE developers SET SALARY = 1900 WHERE ID = '9';
UPDATE developers SET SALARY = 2000 WHERE ID = '10';

